# Generated by Django 4.2.5 on 2023-12-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_category_product_review"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="room_name",
            field=models.CharField(default="EMPTY", max_length=255),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user1",
                to="main.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user2",
                to="main.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.userprofile"
            ),
        ),
    ]
