# Generated by Django 4.2.5 on 2023-11-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
