# Generated by Django 4.2.5 on 2023-11-25 01:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("vendedor", "Vendedor")],
                default=main.models.get_default_role,
                max_length=20,
            ),
        ),
    ]
